- hosts: all
  tasks:
    - debug: "msg='System ansible_hostname {{ ansible_hostname }} has uuid {{ ansible_product_uuid }}'"
    - debug: "msg='System inventory_hostname {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}'"
    - debug: "msg='System ssh port : {{ssh_port}}'"
    - debug: "msg='System ssh tunnel port : {{ssh_tunnel_port}}'"