language: python
python: '2.7'
sudo: required
addons:
  apt:
    sources:
      - python-apt
      - python-pycurl
before_install:
  - sudo apt-get update -qq
install:
  - pip install --upgrade pip
  - pip install ansible netaddr
  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - cp settings_field_node.yml.template settings_field_node.yml
  - cp settings_manager.yml.template settings_manager.yml
env:
  global:
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local
script:
  - ansible-playbook --syntax-check -i test/inventory test/playbook.yml
  - ansible-playbook --syntax-check -i test/inventory management-node/manager-base.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-base.yml
  #- ansible-playbook -i test/inventory test/playbook.yml --connection=local --sudo -vvvv
