language: python
python: '2.7'
sudo: required
addons:
  apt:
    sources:
      - python-apt
      - python-pycurl
before_install:
  - sudo apt-get update -qq
install:
  - pip install --upgrade pip
  - pip install ansible netaddr
  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - cp settings_field_node.yml.template settings_field_node.yml
  - cp settings_manager.yml.template settings_manager.yml
env:
  global:
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local
script:
  - ansible-playbook --syntax-check -i test/inventory test/playbook.yml
  - ansible-playbook --syntax-check -i test/inventory management-node/manager-base.yml
  - ansible-playbook --syntax-check -i test/inventory management-node/manager-sensu.yml
  # ansible as of 2.0.0.2 has a bug where syntax checking fails if vars_prompt is used
  # once it has been resolved, node-full.yml or node-*.yml can be used
  - ansible-playbook --syntax-check -i test/inventory field-node/node-full.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-tunnel.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-users.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-base.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-restart-autossh.yml
  #- ansible-playbook --syntax-check -i test/inventory field-node/compile-and-install-python2.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-dx-uploader.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-geoip.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-mounts.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-power-policy.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-samba.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-sensu.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-tunnel.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/node-users.yml
  - ansible-playbook --syntax-check -i test/inventory field-node/set-sources-list-to-old-release.yml

  #- ansible-playbook -i test/inventory test/playbook.yml --connection=local --sudo -vvvv
