---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Fail2Ban
- import_playbook: fail2ban-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_playbook: fail2ban-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes

# SSH
- import_playbook: ssh.yml

# Autoupdate
- import_playbook: autoupdate-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_autoupdate_enabled

- import_playbook: autoupdate-Debian.yml
  when: ansible_os_family == 'Debian' and security_autoupdate_enabled
