- hosts: nodes
  vars_files:
    - "../settings_field_node.yml"
  vars:
    samba_shares: []
    samba_service_names: ['smbd','nmbd']
    samba_default_globals:
      browseable: 'no'

    seqdata_archival_path: "/media/seqdata"
    move_data_older_than_days: "7"

  vars_prompt:
    - name: "samba_username"
      prompt: "Enter samba username"
      private: no

    - name: "samba_user_password"
      prompt: "Enter samba user password"
      private: yes

  roles: 
    - debops.samba

  tasks:
    - name: add samba user for shared data directory
      user: 
        name: "{{ samba_username }}"
        comment: "samba user for shared data directory" 
        shell: /usr/sbin/nologin

    - name: set samba user password
      shell: "(echo {{ samba_user_password }}; echo {{ samba_user_password }}) | smbpasswd -s -a {{ samba_username }}"

    - name: restart samba services
      service: 
        name: "{{ item }}" 
        state: "restarted"
      with_items: "{{ samba_service_names }}"

    - name: Copy in data moving script (for old data)
      template: 
        src: "./files/move_old_subdirs.sh" 
        dest: "/opt/field-node/move_old_subdirs.sh"
        mode: "0744"

    # this script will be called hourly, but its action should be performed as a post-upload hook
    # with the cron job as a fallback
    - cron: 
        name: "move old data" 
        special_time: "hourly" 
        state: "present"
        job: "/opt/field-node/move_old_subdirs.sh {{ samba_homes_path }}/{{samba_username}} {{ seqdata_archival_path }} {{ move_data_older_than_days }}"

    - debug:
        msg: "User samba home created: {{ samba_homes_path }}/{{samba_username}}"