---
# tasks file for sensu
- include_tasks: common.yml

- include_tasks: server.yml
  when: sensu_install_server

- include_tasks: uchiwa.yml
  when: sensu_install_server and sensu_install_uchiwa

- include_tasks: client.yml
  when: sensu_install_client